services:
  letterboxd_stats:
    image: letterboxd_stats
    container_name: letterboxd_stats
    network_mode: 'host'
    tty: true
    volumes:
      - type: bind
        source: ./config/
        target: /home/app_user/.config/letterboxd_stats/
      - type: bind
        source: ../scripts/
        target: /scripts/
    command: letterboxd_stats -d; tail -f /dev/null
    restart: 'unless-stopped'
