services:

  db:
    image: postgres
    container_name: homelab_db
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      - POSTGRES_USER: "${POSTGRES_USER}"
    volumes:
      - db:/var/lib/postgresql/data
